version: "{build}"

skip_tags: true

os: Visual Studio 2015

init:
  - git config --global core.autocrlf input

install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - ps: .\appveyor.install.ps1

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "$(ASSEMBLY_VERSION)"
  assembly_file_version: "$(ASSEMBLY_FILE_VERSION)"
  assembly_informational_version: "$(ASSEMBLY_INFORMATIONAL_VERSION)"

platform: Any CPU

configuration: Release

build:
  verbosity: minimal
  publish_nuget: true

before_build:
  - set > environment.txt
  - ps: .\appveyor.before_build.ps1

cache:
  - packages -> **\packages.config
  - .nuget -> appveyor.before_build.ps1

deploy:
  - provider: GitHub
    on:
      RELEASE: true
    artifact: /.*\.nupkg/
    tag: $(RELEASE_TAG)
    release: $(RELEASE_TITLE)
    description: $(RELEASE_NOTES)
    prerelease: $(PRERELEASE)
    auth_token:
      secure: ORKZkqGuK16Wfn5LmCxSkhfJhys51oJnPy4kCVHy3QYrgz8zUxZWrN78Tk361jJg
  - provider: NuGet
    on:
      RELEASE: true
    artifact: /.*\.nupkg/
    api_key:
      secure: 9Wg2LEAupBmopvEh2VuikmrE32UwhsTWRsbXwhBnYspDELPopHrV3GjnCkj+WuWT

notifications:
  - provider: Slack
    auth_token:
      secure: ZNvXZbUwux78d01rwXvMvCeXfPLFJ9soBT/ptmI8GYtNcAFuc9jASPUmW6LrxSOm
    channel: development
